.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, src/jax_quantity/_core.py, src/jax_quantity/_register_dispatches.py, src/jax_quantity/_register_primitives.py
Use exact astropy method names, not what I wish they were.
=> use exact astropy method names

src/unxt/_base.py, src/unxt/_distance.py, src/unxt/_register_primitives.py
Operations on Distance don't necessarily result in a distance. We need to promote quantities to the correct type. This PR handles promotion through a mixture of specific dispatch rules and `plum.promote` with new promotion and conversion rules for AbstractQuantity and Distance.
=> fix: promotion in Distance

pyproject.toml, src/unxt/__init__.py, src/unxt/_interop/unxt_interop_gala/unitsystems.py, src/unxt/_unxt/unitsystems/base.py, src/unxt/_unxt/unitsystems/builtin.py, src/unxt/_unxt/unitsystems/builtin_dimensions.py, src/unxt/_unxt/unitsystems/compare.py, src/unxt/_unxt/unitsystems/core.py, src/unxt/_unxt/unitsystems/realizations.py, src/unxt/_unxt/unitsystems/utils.py, src/unxt/unitsystems.py, tests/unit/test_quantity.py, tests/unit/test_unitsystems.py
This PR refactors the unit systems to be more class-based, allowing for static analysis of the unit systems. For users the focus shifts from the `UnitSystem` class to the `unitsystem` function which can dynamically create new unit systems classes, or use statically-defined ones.
Features:
- dataclass constructions
- static analysis
=> feat: unit system refactor

src/unxt/_unxt/unitsystems/base.py, src/unxt/_unxt/unitsystems/realizations.py, tests/unit/test_unitsystems.py
This deserves more thought.
I think perhaps a `.preferred()` method would be better.
=> fix: roll back preferred units

src/unxt/_src/units/system/core.py, src/unxt/_src/units/system/flags.py, src/unxt/unitsystems.py, tests/unit/test_unitsystems.py
This adds a new (currently not used) set of `Flag` types so we can dispatch on the type of unit system (will be useful for the follow-up to add a new `SimulationUnitSystem`). This also adds the ability to extend or override units in an existing unit system via:
```python
>>> usys = unitsystem(...)
>>> new_usys = unitsystem(usys, u.pc, u.erg)
```
=> Add concept of unitsystem flags and enable overriding / extending unit systems

pyproject.toml, src/unxt/_src/units/system/core.py, src/unxt/_src/units/system/flags.py, tests/unit/test_unitsystems.py, uv.lock
This is to add support for unit systems where only two of three of `{length, mass, time}` units need to be specified because the value of G is set to 1 (or some other value). This is analogous to Gala's [`SimulationUnitSystem`](http://gala.adrian.pw/en/latest/api/gala.units.SimulationUnitSystem.html#gala.units.SimulationUnitSystem).
For the value of G, I was originally planning to accept `unxt.Quantity | float | int`. But I think this needs to be a concrete value as the computed units need to be passed to `unxt.units()`, which under the hood calls `astropy.units.Unit`. So the current approach accepts `astropy.units.Quantity | float | int`, but now I'm thinking that this should instead require only `float | int` because it doesn't really make sense to allow someone to pass in a unit-ful G. …
=> Add support for dynamical simulation unit systems (G=1 or other value)

src/unxt/_src/units/system/builtin.py
=> Fix typo in SI

src/unxt/__init__.py, src/unxt/_interop/unxt_interop_astropy/quantity.py, src/unxt/_interop/unxt_interop_mpl/__init__.py, src/unxt/_src/quantity/compat.py, src/unxt/_src/quantity/fast.py, src/unxt/_src/quantity/mixins.py, src/unxt/_src/quantity/register_primitives.py, tests/unit/test_quantity.py
Use the `unxt.quantity` module to access them. Keeps the top-level very clean.
=> refactor: remove uncommon Q classes from top ns

pyproject.toml
Small edit to pyproject.toml so that it no longer installs with pip on unsupported Python versions.
=> Disallow version 3.13

.github/workflows/ci.yml, pyproject.toml, src/unxt/_interop/unxt_interop_astropy/quantity.py, src/unxt/_src/quantity/base.py
A draft for Python 3.13 compatibility. Currently solving none of the bugs, but simply updating the CI matrix to test all versions of supported Python and updating the pyproject.toml to have the 3.13 tag while disallowing 3.14.
=> Python 3.13 Support

pyproject.toml, uv.lock
Signed-off-by: nstarman <nstarman@users.noreply.github.com>
(cherry picked from commit 9fb427b40d93915f208219846d35c5db0f9db8a3)
=> Backport PR #321 on branch versions/v1.0.x (🔧 config(uv): add temporary jax constraint)

pyproject.toml, src/unxt/_interop/unxt_interop_astropy/quantity.py, src/unxt/_src/experimental.py, src/unxt/_src/quantity/api.py, src/unxt/_src/quantity/base.py, src/unxt/_src/quantity/compat.py, src/unxt/_src/quantity/functional.py, src/unxt/_src/quantity/mixins.py, src/unxt/_src/quantity/register_primitives.py, src/unxt/_src/units/core.py
Similar to `.value`, but enables flexibility in, e.g. applying a wrap angle when computing the value.
=> ✨ feat(quantity): single-argument ustrip

src/unxt/_src/quantity/base.py, src/unxt/_src/quantity/base_parametric.py, src/unxt/_src/quantity/core.py, src/unxt/_src/quantity/fast.py, src/unxt/_src/quantity/mixins.py, tests/unit/test_quantity.py
No change to API, just ensuring the abstract classes are abstract.
=> ♻️ refactor(quantity): ensure abstract quantities are abstract

.pre-commit-config.yaml, pyproject.toml
enable mutually exclusive extra dependencies
=> ➕ dep-add(extras): add extra dependencies

.github/workflows/ci.yml, pyproject.toml, tests/benchmark/test_dimensions.py, tests/benchmark/test_quaxed.py, tests/benchmark/test_units.py, uv.lock
A followup pr is necessary to get codspeed running the tests faster.
Also one to make a cron job.
=> TST: benchmarks

src/unxt/_src/quantity/__init__.py, src/unxt/_src/quantity/base.py, src/unxt/quantity.py, uv.lock
This is useful for jax.tree is_leaf filtering.
=> ✨ feat(quantity): add a function is_any_quantity checking isinstance(x, AbstractQuantity)

.github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, src/unxt/_src/experimental.py, src/unxt/_src/quantity/base.py, src/unxt/_src/quantity/mixins.py, src/unxt/_src/quantity/register_primitives.py, src/unxt/_src/utils.py, tests/integration/quaxed/test_numpy.py, tests/unit/test_quantity.py, uv.lock
The `quaxed.experimental.arrayish` provides building blocks for constructing array-ish objects. After that the primitives need to be registered.
This PR refactors Quantity to use these blocks.
Since we vendor `quaxed`, using the experimental module is alright. The problems in that module — typing and lax —  aren't impactful here.
=> 👽️ external(quaxed): use new quaxed.experimental.arrayish module

src/unxt/__init__.py, uv.lock
This is good for users in 2 primary use cases.
1. Makes isinstance checks for ANY quantity type easier (`isinstance(x, u.AbstractQuantity)` vs `isinstance(x, u.quantity.AbstractQuantity)`
2. Makes type annotations shorter / fewer imports.
=> 💄 ui(quantity): make AbstractQuantity available from the unxt namespace

docs/glossary.md, docs/guides/type-checking.md, src/unxt/_interop/unxt_interop_astropy/quantity.py, src/unxt/_interop/unxt_interop_mpl/__init__.py, src/unxt/_src/experimental.py, src/unxt/_src/quantity/__init__.py, src/unxt/_src/quantity/register_conversions.py, src/unxt/_src/quantity/register_primitives.py, src/unxt/_src/quantity/unchecked.py, src/unxt/quantity.py, tests/benchmark/test_quaxed.py, tests/unit/test_deprecated.py
=> 💥 boom(quantity): rename UncheckedQuantity to BareQuantity

src/unxt/_src/quantity/flag.py, src/unxt/_src/quantity/register_conversions.py, src/unxt/quantity.py
This assumes the value to be in the right unit.
This will simplify code in `galax`, where the assumption about values having the right units is common.
=> ✨ feat(quantity): AllowValue flag to let ustrip work on non-quantities

docs/conventions.md, docs/guides/quantity.md, docs/guides/type-checking.md, docs/index.md, docs/interop/astropy.md, pyproject.toml, src/unxt/_interop/unxt_interop_astropy/quantity.py, src/unxt/_src/experimental.py, src/unxt/_src/quantity/api.py, src/unxt/_src/quantity/base.py, src/unxt/_src/quantity/base_parametric.py, src/unxt/_src/quantity/mixins.py, src/unxt/_src/quantity/quantity.py, src/unxt/_src/quantity/register_api.py, src/unxt/_src/quantity/register_conversions.py, src/unxt/_src/quantity/register_dispatches.py, src/unxt/_src/quantity/register_primitives.py, uv.lock
This changes the string representation machinery to use the Wadler-Lindig library. 
See https://docs.kidger.site/wadler_lindig/.
There's now a lot more flexibility to format the strings.
I also make the nice change that `repr` doesn't show the [dimension] since this is currently uniquely determined by the unit.
The `str` does show it, and instead abbreviates the array.
This will help a lot with nicer formatting in `coordinax` and `galax`.
Note that Equinox already has W-L as a dependency, so this isn't really adding any new dependencies.
=> feat: use wadler_lindig

.pre-commit-config.yaml, docs/guides/quantity.md, src/unxt/_src/quantity/base.py, src/unxt/_src/quantity/base_parametric.py, src/unxt/_src/quantity/quantity.py
All arrays are jax arrays, so the kind is not necessary.
Resolved using answer in https://github.com/patrick-kidger/wadler_lindig/issues/7
=> 🐛 fix(quantity): printing with short_array no longer appends the kind

.github/workflows/cd.yml
Potential fix for [https://github.com/GalacticDynamics/unxt/security/code-scanning/2](https://github.com/GalacticDynamics/unxt/security/code-scanning/2)
To fix the issue, we need to add a `permissions` block to the `dist` job in the workflow file `.github/workflows/cd.yml`. The permissions should be set to `contents: read`, as this is the minimal privilege required for the job to perform its tasks. This change ensures that the job does not have unnecessary write access to the repository.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 2: Workflow does not contain permissions
