- src/jax_quantity/_register_dispatches.py
- src/jax_quantity/_register_primitives.py
> fix units arg to replace

- .pre-commit-config.yaml
- docs/conf.py
- noxfile.py
- pyproject.toml
- src/jax_quantity/__init__.py
- src/jax_quantity/_core.py
- src/jax_quantity/_register_dispatches.py
- src/jax_quantity/_register_primitives.py
> Add pylint

- src/jax_quantity/_register_primitives.py
> use DenseArrayValue instead of Value

- .pre-commit-config.yaml
- pyproject.toml
- src/jax_quantity/_core.py
- src/jax_quantity/_register_dispatches.py
- src/jax_quantity/_register_primitives.py
- tests/test_array_api_jax_compat.py
- tests/test_quantity.py
> build: bump quax >= 0.0.3

- pyproject.toml
- src/jax_quantity/_core.py
- src/jax_quantity/_register_primitives.py
- tests/test_quantity.py
It would be good to figure out compatibility with `jaxtyping`. For a followup.
> feat: parametric Quantity[dimensions]

- conftest.py
- pyproject.toml
- src/jax_quantity/_register_primitives.py
Also some infrastructure improvements
> feat: dot general

- src/jax_quantity/_core.py
> feat: hash method

- pyproject.toml
- src/jax_quantity/__init__.py
- src/jax_quantity/_base.py
- src/jax_quantity/_core.py
- src/jax_quantity/_fast.py
- src/jax_quantity/_register_primitives.py
- tests/test_array_api_jax_compat.py
A version of Quantity that is not parametric. It's faster, though it would be nice to have benchmark tests to demonstrate this over time.
> feat: UncheckedQuantity

- pyproject.toml
- src/unxt/__init__.py
- src/unxt/_typing.py
- src/unxt/unitsystems.py
> feat: unitsystems

- src/unxt/unitsystems.py
Also sped up dispatch of unitsystems by str name
> feat: NAMED_UNIT_SYSTEMS registry

- src/unxt/_quantity/distance.py
Make a Distance class hierarchy.
AbstractQuantity -> AbstractDistance -> Distance
-> Parallax
In particular, Parallax permits negative parallaxes, like from Gaia
> feat: parallax distance

- pyproject.toml
- src/unxt/_utils/__init__.py
- src/unxt/_utils/optional_deps.py
- src/unxt/unitsystems/__init__.py
- src/unxt/unitsystems/_compat.py
- tests/quaxed/test_array_api.py
Moved from galax.
I'm considering this a bug release since you needed galax to get the desired behaviour from unxt!
> feat: gala compat

- src/unxt/_quantity/base.py
- tests/test_quantity.py
> feat: at[] property

- src/unxt/_interop/unxt_interop_astropy/quantity.py
- src/unxt/_unxt/quantity/functional.py
There aren't really any optimized forms of `to_units().value`.
> feat: rm to_units_value

- src/unxt/__init__.py
- src/unxt/_interop/unxt_interop_astropy/__init__.py
- src/unxt/_interop/unxt_interop_astropy/units.py
- src/unxt/_unxt/units.py
Creates the `units` and `units_of` functions.
Part of #139.
> feat: units

- src/unxt/__init__.py
- src/unxt/_unxt/dimensions.py
- src/unxt/_unxt/quantity/compat.py
- src/unxt/_unxt/units.py
> feat: dimensions_of

- pyproject.toml
- src/unxt/_src/quantity/register_primitives.py
> fix: ambiguous concat

- src/unxt/_interop/unxt_interop_astropy/quantity.py
- src/unxt/_src/experimental.py
- src/unxt/_src/quantity/api.py
- src/unxt/_src/quantity/base.py
- src/unxt/_src/quantity/compat.py
- src/unxt/_src/quantity/distance.py
- src/unxt/_src/quantity/functional.py
- src/unxt/_src/quantity/register_dispatches.py
- src/unxt/_src/quantity/register_primitives.py
- src/unxt/quantity.py
awaiting functionality from astropy v7
> feat: better unit conversion

- src/unxt/_src/units/system/utils.py
- tests/unit/test_unitsystems.py
> Strip spaces from physical type names

- pyproject.toml
I wasn't sure if I should bump both jax and jaxlib?
@nstarman 
Closes #237
> Update minimum jax/jaxlib versions

- src/unxt/_src/quantity/base.py
- src/unxt/_src/quantity/register_primitives.py
> feat: block_until_ready method

- src/unxt/__init__.py
- src/unxt/_src/dimensions/core.py
- src/unxt/_src/units/core.py
- src/unxt/dims.py
> feat: add dims sub-package

- src/unxt/_src/quantity/register_primitives.py
Register in support for the dynamic_slice primitive
> feat: dynamic_slice_p

- src/unxt/__init__.py
- src/unxt/_interop/unxt_interop_astropy/dimensions.py
- src/unxt/_interop/unxt_interop_astropy/quantity.py
- src/unxt/_interop/unxt_interop_astropy/units.py
- src/unxt/_interop/unxt_interop_gala/unitsystems.py
- src/unxt/_src/dimensions/core.py
- src/unxt/_src/experimental.py
- src/unxt/_src/quantity/api.py
- src/unxt/_src/quantity/base.py
- src/unxt/_src/quantity/base_parametric.py
- src/unxt/_src/quantity/compat.py
- src/unxt/_src/quantity/core.py
- src/unxt/_src/quantity/functional.py
- src/unxt/_src/quantity/mixins.py
- src/unxt/_src/quantity/register_primitives.py
- src/unxt/_src/typing_ext.py
- src/unxt/_src/units/core.py
- src/unxt/_src/units/system/base.py
- src/unxt/_src/units/system/builtin.py
- src/unxt/_src/units/system/builtin_dimensions.py
- src/unxt/_src/units/system/core.py
- src/unxt/_src/units/system/realizations.py
- src/unxt/_src/units/system/utils.py
- src/unxt/dims.py
- src/unxt/units.py
- tests/benchmark/test_quaxed.py
- tests/integration/quaxed/test_numpy.py
- tests/unit/test_quantity.py
- tests/unit/test_unitsystems.py
Following discussion with @adrn
> refactor: rename many functions

- src/unxt/_src/quantity/mixins.py
This just calls out to `quaxed` via the `__array_namespace__`
> feat: support numpy functions

- src/unxt/_interop/unxt_interop_astropy/quantity.py
> fix: equivalencies that change dimensions

- src/unxt/_src/units/__init__.py
- src/unxt/_src/units/api.py
- src/unxt/_src/units/system/base.py
> ♻️ refactor(units): use api module

- pyproject.toml
- src/unxt/_src/quantity/register_primitives.py
- uv.lock
This is one step in enabling quax-compatible arrays, not just jax arrays.
> ♻️ refactor(quantity): redispatch through primitives

- .pre-commit-config.yaml
- pyproject.toml
- src/unxt/_interop/unxt_interop_astropy/dimensions.py
- src/unxt/_interop/unxt_interop_astropy/quantity.py
- src/unxt/_interop/unxt_interop_gala/unitsystems.py
- src/unxt/_src/quantity/api.py
- src/unxt/_src/quantity/base.py
- src/unxt/_src/quantity/base_parametric.py
- src/unxt/_src/quantity/quantity.py
- src/unxt/_src/quantity/register_api.py
- src/unxt/_src/quantity/register_conversions.py
- src/unxt/_src/quantity/register_dispatches.py
- src/unxt/_src/units/api.py
- src/unxt/_src/units/core.py
- src/unxt/_src/units/system/compare.py
- src/unxt/_src/units/system/core.py
- src/unxt/_src/units/system/utils.py
- uv.lock
0 API change, just improves static type checking.
> ⬆️ dep-bump(plum): bump v2.5.5+ for more type info

- src/unxt/_src/quantity/base.py
> 🔥 dump(quantity): rm unused utilities

- src/unxt/_src/quantity/register_primitives.py
(cherry picked from commit 998e682c2b27243a5ebdd12f11a98dd4275e3756)
Signed-off-by: Nathaniel Starkman <nstarman@users.noreply.github.com>
> 🐛 fix(quantity): concat_p for abstract quantity (#389)

- .readthedocs.yaml
- docs/dev.md
- docs/index.md
- noxfile.py
- pyproject.toml
- uv.lock
Same as GalacticDynamics/coordinax#413!
> Enable building docs with Nox

- docs/guides/quantity.md
- src/unxt/_src/quantity/base.py
- uv.lock
> 🐛 fix(quantity): wl of compact_arrays

- src/unxt/_src/quantity/register_primitives.py
- src/unxt/_src/utils.py
> 🐛 fix(quantity): register pad_p
